# docker-compose.yml

version: '3.8' # Especifica a versão do formato do Docker Compose

services:
  # ====================================================================================
  # ===== --- Serviço da API FastAPI ---                                           =====
  # ====================================================================================
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/service/app
      - ./alembic.ini:/service/alembic.ini
      - ./alembic:/service/alembic

    env_file:
      - .env

  # ====================================================================================
  # ===== --- Serviço do Banco de Dados PostgreSQL ---                             =====
  # ====================================================================================
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

# ====================================================================================
# ===== --- Definição de Volumes Nomeados ---                                    =====
# ====================================================================================
volumes:
  postgres_data:
