"""
This type stub file was generated by pyright.
"""

from .BaseDoc import BaseDoc

class CNS(BaseDoc):
    """Classe referente ao Cartão Nacional de Saúde (CNS)."""

    def __init__(self) -> None: ...
    def validate(self, doc: str = ...) -> bool:
        """Validar CNS."""
        ...

    def generate(self, mask: bool = ...) -> str:
        """Gerar CNS."""
        ...

    def mask(self, doc: str = ...) -> str:
        """Coloca a máscara de CPF na variável doc."""
        ...
