"""
This type stub file was generated by pyright.
"""

from .BaseDoc import BaseDoc

class CPF(BaseDoc):
    """Classe referente ao Cadastro de Pessoas Físicas (CPF)."""

    def __init__(self, repeated_digits: bool = ...) -> None: ...
    def validate(self, doc: str = ...) -> bool:
        """Validar CPF."""
        ...

    def generate(self, mask: bool = ...) -> str:
        """Gerar CPF."""
        ...

    def mask(self, doc: str = ...) -> str:
        """Coloca a máscara de CPF na variável doc."""
        ...
